### ISSUE TITLE
Incorrect tau result

### ISSUE THREAD

**Issue by Genarito** [zolkko/kendalls#1]
Hi, first of all thank you for this crate. I've tried with the example from the [docs of Scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kendalltau.html) but I saw that results are different:

**Python**

```python
from scipy.stats import kendalltau

x1 = [12, 2, 1, 12, 2]
x2 = [1, 4, 7, 1, 0]
tau, p_value = kendalltau(x1, x2)
print(tau) # -0.4714045207910316
```

**Rust**

```rust
let x = vec![12, 2, 1, 12, 2];
let y = vec![1, 4, 7, 1, 0];
let tau = kendalls::tau_b(&x, &y).unwrap();
println!("{}", tau); // -0.7071067811865476
```

I saw that in both docs the formula is `tau = (P - Q) / sqrt((P + Q + T) * (P + Q + U))` so I don't know if there's something I'm missing or It's a bug.

Thanks in advance and sorry about my English

**Comment by kunc** [comment]
Hi,
I am also getting different results compared to the scipy implementation.
```rust
let x: Vec<f64> = vec![1.0, 1.0, 2.0, 2.0, 3.0, 3.0];
let y: Vec<f64> = vec![1.0, 2.0, 2.0, 3.0, 3.0, 4.0];
let res = kendalls::tau_b_with_comparator(&x[..], &y[..], |a: &f64, b: &f64| a.partial_cmp(&b).unwrap_or(Ordering::Greater)); 
// 0.48038446141526137
```
while
```python
from scipy.stats import kendalltau
x = [1.0, 1.0, 2.0, 2.0, 3.0, 3.0]
y = [1.0, 2.0, 2.0, 3.0, 3.0, 4.0]
res = kendalltau(x, y)
# 0.8006407690254358
```
I am using `scipy==1.4.1` and your crate `kendalls = "0.1.2"`.

**Comment by zolkko** [comment]
Hi guys,

@Genarito , @kunc 
I am sorry for the late response. I totally have missed your messages. I confirm that this is a bug.
Thanks for the reporting it.

**Comment by zolkko** [comment]
Fixed in https://github.com/zolkko/kendalls/commit/2dc5ca1cb85c14fd44829156c3e533dbf71cb1b9 and published to crates.io version "0.1.4"

**Comment by Genarito** [comment]
Hi @zolkko ! Sorry but this issue should be re-open as I've found a difference between Scipy, [an online calculator](https://www.wessa.net/rwasp_kendall.wasp#output) and this crate:

**Python:**

```python
from scipy.stats import kendalltau

x1 = [12.0, 14.0, 14.0, 17.0, 19.0, 19.0, 19.0, 19.0, 19.0, 20.0, 21.0, 21.0, 21.0, 21.0, 21.0, 22.0, 23.0, 24.0, 24.0, 24.0, 26.0, 26.0, 27.0]
x2 = [11.0, 4.0, 4.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0]

tau, p_value = kendalltau(x1, x2)
print(tau)  # -0.37620154104750975
```

**Rust:**

```rust
use std::cmp::Ordering;

fn main() {
    let x = vec![
        12.0, 14.0, 14.0, 17.0, 19.0, 19.0, 19.0, 19.0, 19.0, 20.0, 21.0, 21.0, 21.0, 21.0, 21.0,
        22.0, 23.0, 24.0, 24.0, 24.0, 26.0, 26.0, 27.0,
    ];
    let y = vec![
        11.0, 4.0, 4.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0,
        0.0, 0.0, 0.0, 0.0, 0.0,
    ];

    let tau = kendalls::tau_b_with_comparator(&x, &y, |a: &f64, b: &f64| {
        a.partial_cmp(&b).unwrap_or(Ordering::Greater)
    }).unwrap();
    println!("{}", tau); // -0.34037282285250886
}
```

Both Python and the web calculator has the same value for correlation but there's a difference of ~0.0358 with Rust

**Comment by zolkko** [comment]
@Genarito  Thanks again for reporting the issue!
Fixed the bug.  https://github.com/zolkko/kendalls/commit/cecd758631083000927df94e4d35d9e7fa94b41b

**Comment by zolkko** [comment]
@Genarito  Added a kind of test https://github.com/zolkko/kendalls-py/blob/master/tests.py that compares results of this crate and scipy. That is far from an ideal solution, but it is better than nothing =]. I will try to cover all cases with real unit tests, when I have some free time.

**Comment by Genarito** [comment]
You're the best! Thank you!
