### ISSUE TITLE
Significance Z value seems to be wrong

### ISSUE THREAD

**Issue by Genarito** [zolkko/kendalls#2]
Hi, first of all sorry for being a nightmare. I'm trying to get the p-value from your significance value Z but it's different from some libraries. Computing the Z value with [this calculator](https://astatsa.com/CorrelationTest/) with the data below gives me `Z = -2.09764910069 `

**Data to test in calculator**:

```
   A    B
 12  11
 14  4
 14  4
 17  2
 19  0
 19  0
 19  0
 19  0
 19  0
 20  0
 21  4
 21  0
 21  4
 21  0
 21  0
 22  0
 23  0
 24  4
 24  0
 24  0
 26  0
 26  0
 27  0
```

But if you replicate the experiment in Rust:

```rust
use std::cmp::Ordering;

fn main() {
    let x = vec![
        12.0, 14.0, 14.0, 17.0, 19.0, 19.0, 19.0, 19.0, 19.0, 20.0, 21.0, 21.0, 21.0, 21.0, 21.0,
        22.0, 23.0, 24.0, 24.0, 24.0, 26.0, 26.0, 27.0,
    ];
    let y = vec![
        11.0, 4.0, 4.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 4.0,
        0.0, 0.0, 0.0, 0.0, 0.0,
    ];

    let tau = kendalls::tau_b_with_comparator(&x, &y, |a: &f64, b: &f64| {
        a.partial_cmp(&b).unwrap_or(Ordering::Greater)
    }).unwrap();

    let significance = kendalls::significance(tau, x.len());
    println!("{}", significance); // -2.513720561126002
}
```

If I select a fixed Z value as the one thrown by the online calculator the p-value is similar to R code, Python and [this other web tool](https://www.wessa.net/rwasp_kendall.wasp#output).

Is there I'm missing?

**Comment by Genarito** [comment]
@zolkko  I've found the problem: It's computing Tau B value but the significance algorithm is for Tau A. For Tau B is another formula. [Source](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient#Significance_tests). If you have no time to fix it I'll try, but I've to learn some things first

**Comment by Genarito** [comment]
Hi @zolkko! How are you?
Is there any update on this? Is there something in which I could help you?

**Comment by zolkko** [comment]
@Genarito  hope you are doing well!

The only thing I did so far is preliminary research. I looked through Python/R implementations. And I was hoping to reach out to one of my colleges, who, I believe, can explain to me those approximations of the distribution.
But even right now, it is clear that the correlation function would have to return a more complicated type (than f64) that internally holds tie counters.
So, I plan to talk to the college this week and start implementing something during the weekend.

**Comment by Genarito** [comment]
Cool! I've tried to read the code and implement, but significance for Tau-b is much more complex than the one for Tau-a! Sorry!  Hope you can solve it :D

**Comment by matiasbutti** [comment]
Hi @zolkko. I have run into the same problem described by @Genarito.
Have you been able to find the solution or some workaround?
Thank you!

**Comment by zolkko** [comment]
Hi @matiasbutti! I am not aware of any workaround unless you are willing to use pyo3 or Spearman correlation from gsl library. I am porting scipy's implementation, but work is going slowly for many non-technical reasons ... only God knows why, in short. =]

**Comment by Genarito** [comment]
Don't worry @zolkko! Hope you can solve your problems!

Maybe a workaroud, as you said, is to use pyo3 to call [Scipy's KendallTau function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kendalltau.html) until this issue is solved.

Thank you!

**Comment by matiasbutti** [comment]
Thanks @zolkko! I'm going to try with pyo3.

**Comment by Genarito** [comment]
Hi @zolkko. I've made a PR (#3) which fixes this issue. Just a reminder in case you missed it  :D
